### ISSUE TITLE
How to enable feedit (help needed)

### ISSUE THREAD

**Issue by cgpro** [benjaminkott/site-introduction#10]
Is this guide still valid with TYPO3 9.5.5? (feedit, NOT frontend_editing)
https://wiki.typo3.org/Frontend_editing
I can't get it to work. :( I've activated the checkboxes 'display edit icons/panels' in the debugbar too.

BTW: I also tried the frontend_editing extension from Pixelant, but it's not very compatible with fluid templates. I hope it will be better with upcoming releases, but for now it's quite useless with fluid templates. (It's only possible to edit simple text boxes... nested elements like in a slider are editable, but you can't save it - the documentation is also a bit poor ... only btw)

**Comment by obreshkov** [comment]
Did you find a solution about frontend editing of bootstrap package developed by Benjamin Kott

**Comment by cgpro** [comment]
Nope. I think frontend editing is not possible right now. :(
